version: '3'
services:
 mysql:
  image: mysql:5.5
  container_name: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_DATABASE: test_db
    MYSQL_USER: user
    MYSQL_PASSWORD: password

 node:
  build: .
  container_name: node
  ports:
    - 3000:3000
  volumes:
    - ./src:/home/app/src
  depends_on:
    - mysql